#! /usr/bin/env/ python
import sys
import posixpath
from getopt import getopt
from flask_start import make_common_project


if __name__ == '__main__':

    opts, _ = getopt(sys.argv[1:], 'n:t:h')

    template = 'common'
    for o, v in opts:
        if o == '-h':
            print __doc__
            sys.exit(0)
        elif o == '-n':
            dir_name = v
        elif o == '-t':
            template = v
        else:
            print 'unknown options: ' + o
            print __doc__
            sys.exit(-1)
    try:
        dir_name
    except NameError:
        print __doc__
        sys.exit(-1)

    if template not in {'common', 'mini', 'flask_databrowser'}:
        print __doc__
        sys.exit(-1)

    if posixpath.exists(dir_name):
        print dir_name + ' already exists!'
        sys.exit(-1)
    if template == 'common':
        make_common_project(dir_name)
